apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels: 
    app: backend-deploy
spec:
  template: 
    metadata:
      labels:
        app: helpqueue-backend
    spec: 
      containers:
      - name: backend-container
        image: schan69/helpqueue-backend:latest
        ports:
        - containerPort: 8080
  replicas: 3
  selector:
    matchLabels:
      app: helpqueue-backend