apiVersion: v1
kind: Service
metadata:
  name: helpqueue-lb
spec:
  type: LoadBalancer
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
  - name: backend
    protocol: TCP
    port: 8080
    targetPort: 8080
  
  selector:
    app: nginx